[MISSING_PAGE_FAIL:1]

* Joutz and Stekler (1971)**Joutz, F.** and **H.O. Stekler,** An evaluation of the predictions of the Federal Reserve (1) 17- 38
* Kennedy (1974)**Kennedy, M.,**_see Adya, M._
* Klapper and Herwartz (1975)**Klapper, D.** and **H. Herwartz,** Forecasting market share using predicted values of competitive behavior: further empirical results (3) 399-421
* Klein (2012)**Klein, P.A.,**_see Banerji, A._
* Kumar (1975)**Kumar, V.,**_see Armstrong, J.S._
* Lahiri (1976)**Lahiri, K.,**_see Ivanova, D._
* Lawrence (1976)**Lawrence, M.,** Editorial: What does it take to achieve adoption in sales forecasting? (2) 147-148
* Lawrence (1977)**Lawrence, M.** and **M. O'Connor,** Sales forecasting updates: how good are they in practice? (3) 369-382
* Leung (2012)**Leung, M.T., H. Daouk and A.-S. Chen,** Forecasting stock indices: a comparison of classification and level estimation models (2) 173-190
* Ludlow and Enders (1975)**Ludlow, J.** and **W. Enders,** Estimating non-linear ARMA models using Fourier coefficients (3) 333-347
* Mady (1976)**Mady, M.T.,** Sales forecasting practices of Egyptian public enterprises: survey evidence (3) 359-368
* Makridakis (1977)**Makridakis, S.,**_see Ord, K._
* Makridakis and Hibon (1978)**Makridakis, S.** and **M. Hibon,** The M3-Competition: results, conclusions and implications (4) 451-476
* McCullough (1979)**McCullough, B.D.,** Is it safe to assume that software is accurate?
* Meade (1979)**Meade, N.,** A note on the Robust Trend and ARARMA methodologies used in the M3 Competition
* Melard and Pasteels (1979)**Melard, G.** and **J.-M. Pasteels,** Automatic ARIMA modeling including interventions, using time series expert software (4) 497-508
* Morwitz (1979)**Morwitz, V.G.,**_see Armstrong, J.S._
* Nikolopoulos (1979)**Nikolopoulos, K.,**_see_ **Assimakopoulos, V.**
* Oller and Barot (1979)**Oller, L.-E.** and **B. Barot,** The accuracy of European growth and inflation forecasts (3) 293-315
* Ord (1979)**Ord, J.K.,**_see_ **Balkin, S.D.**
* Ord and Makridakis (1979)**Ord, K.,** M. Hibon** and **S. Makridakis,** The M3-Competition (4) 433-436
* O'Connor and Remus (1979)**O'Connor, M.,** W. Remus** and **K. Griggs,** Does updating judgmental forecasts improve forecast accuracy? (1) 101-109
* O'Connor (1979)**O'Connor, M.,**_see_ **Lawrence, M.**
* Pace et al (2022)**Pace, R.K., R. Barry, O.W. Gilley** and **C.F. Sirmans,** A method for spatial-temporal forecasting with an application to real estate prices (2) 229-246
* Pasteels and Melard (1979)**Pasteels, J.-M.,**_see_ **Melard, G.**
* Pearce and Flores (1979)**Pearce, S.L.**_see_ **Flores, B.E.**
* Proietti (1979)**Proietti, T.,** Comparing seasonal components for structural time series models (2) 247-260
* Remus (1979)**Remus, W.,**_see_ **O'Connor, M.** (1) 101-109
* Seitz and Ivanova (1979)**Seitz, F.,**_see_ **Ivanova, D.** (1) 39- 58
* Simmons (1979)**Simmons, R.,**_see_ **Forrest, D.** (3) 317-331
* Sirmans (2020)**Sirmans, C.F.,**_see_ **Pace, R.K.** (2) 229-246
* Slama and Darbellay (1979)**Slama, M.,**_see_ **Darbellay, G.A.** (1) 71- 83
* Sotca (1979)**Sotca, S.,**_see_ **Casals, J.** (1) 59- 69
* Stekler (1979)**Stekler, H.O.,**_see_ **Joutz, F.** (1) 17- 38
* Tashman (1979)**Tashman, L.J.,** Out-of-sample tests of forecasting accuracy: an analysis and review (4) 437-450
* Thomas (1979)**Thomas, L.C.,** A survey of credit and behavioural scoring: forecasting financial risk of lending to consumers (2) 149-172