Many new developments in research methodology receive an unduly warm welcome from proponents of received wisdom and this maxim certainly held true for forecasting competitions, as the account in Fildes and Makridakis (1995) amply illustrates.

The first major paper to report a forecasting competition was that of Newbold and Granger (1974), who followed up on earlier studies by Reid (1969, 1972). However, it is arguably the 1979 paper by Makridakis and Hibon that brought the subject into controversial center-stage. This paper was read to the Royal Statistical Society and generated the kind of vigorous discussion for which that Society is justly famed. Since that time, many additional and larger studies have appeared, including the M-Competition (Makridakis et al., 1982), the M2-Competition (Makridakis et al., 1993), and the studies by Meese and Geweke (1984) and by Fildes et al. (1998). For further details the reader should consult Fildes and Makridakis (1995) and Fildes and Ord (2000).

Over the years, some substantial improvements in methodology have emerged, notably in such areas as the selection of accuracy measures and the use of multiple forecasting origins. On the other hand, some issues remain contentious: how far can the results of one and even many such competitions provide a basis for inference about the performance of forecasting procedures? Our role as editors is not to take a "party line" on such matters; indeed, we agree on some topics but not on others. Rather, our objective is to provide an informed basis for discussion. Therefore, in the papers that appear in this special issue, the reader will find an appraisal of current methods, a detailed reporting of the M3-Competition and several short papers describing methods that were developed with large-scale forecasting tasks in mind. There will be a follow-up section in a later issue of the _Journal_ in which we provide an edited discussion from a range of forecasting experts.

The first paper in this special issue is by Len Tashman on "Out-of-Sample Tests of Forecasting Accuracy: An Analysis and Review." In this paper, Tashman describes the structure of out-of-sample tests of forecasting performance and provides guidelines for effective implementation. He also reviews the progress made towards the implementation of these methods in existing software.

The second paper "The M3-Competition: Results, Conclusions and Implications" by Spyros Makridakis and Michele Hibon (1979) is the principal paper in this special issue and provides a detailed description of the M3-Competition and the results. After providing a brief history of forecasting competitions, the authors describe the structure of the M3-Competition and list the methods used by the researchers who contributed to the study. New forecasting methods are described in other papers in the special issue, and are outlined below. The paper then summarizes the results of the competition. This section includes only a limited number of conclusions, since the major purpose of the paper is to lay out the results for further discussion. Additional summary results are provided on the Internet site [http://www.inead.fr/facultyresearch/forecasting.html](http://www.inead.fr/facultyresearch/forecasting.html).

Any forecasting system designed to handle large numbers of series, as in the M3-Competition, must either be very simplistic ("one method fits all") or rely upon (nearly) automated rules for model selection. The next five papers describe some very different approaches to model selection (or model identification in the terminology of Box and Jenkins) and describe their application to the M3-Competition time series.

In "An Application of Rule-Based Forecasting to a Situation Lacking Domain Knowledge," Monica Adya, Scott Armstrong, Fred Collopy and Miles Kennedy describe a modified approach to rule-based forecasting (RBF) that builds upon earlier work by Collopy and Armstrong (1992). This scheme incorporates greater automation to allow for the large number of forecasting tasks to be completed and the rule base is modified to allow for the absence of any substantive domain knowledge, a constraint forced upon the authors by the nature of the M3-Competition.

Benito Flores and Stephen Pearce also consider a rule-based system in "The Use of an Expert System in the M3-Competition". In this research the rules guide selection from a set of exponential smoothing and decomposition procedures, with and without seasonal structure. The authors considered two systems, one of which was purely automated whereas the other allowed expert intervention in the model selection process.

Guy Melard and Jean-Michel Pasteels describe an automatic forecasting system for ARIMA modeling in their paper "Automatic ARIMA Modeling Including Interventions, Using Time Series Expert Software". The system pays particular attention to decisions on transformations and differencing, and on model specification. In addition, the system includes a cycle of model checking and revised model specification. Intervention analysis may be used at the researcher's discretion.

Artificial Neural Networks (ANN) have generated considerable interest in forecasting circles in recent years. In "Automatic Neural Net Modeling for Univariate Time Series," Sandy Balkin and Keith Ord provide a framework for forecasting using ANNs that incorporates a systematic model selection procedure. The appeal of ANNs is their ability to handle nonlinear structure and the authors assess the value of this added generality in the context of the M3-Competition.

The dominant approaches to forecasting use linear models with (at least implicitly) differencing to remove trends and least squares for estimation. In "A Note on the Robust Trend and ARARMA Methodologies Used in the M3-Competition," Nigel Meade explores automated systems based respectively upon robust estimation and on Parzen's (1982) long-term trend approach.

The final paper in the special issue follows a different and surprisingly successful approach. In "The Theta Model: A Decomposition Approach to Forecasting" Vassilis Assimakopoulos and Kostas Nikolopoulos first remove any seasonal pattern by a classical decomposition procedure and then decompose the series into two parts. In essence, these two components may be viewed as a trend line to describe longer-term behavior and a second difference for short-term movements. These components are then extrapolated separately and the elements recombined to produce the final forecasts. The effectiveness of this approach adds further fuel to the continuing debate about the relative merits of fixed and stochastic seasonal and trend components.

One of the objectives of the M3-Competition was to evaluate the performance of the leading commercial software packages in the forecasting area. Five vendors accepted the invitation to participate in the study and their results are reported in the main Makridakis-Hibon paper along with all the other analyses. In order to provide readers of the Special Issue with background details on these packages, we invited each of the participants to contribute factual accounts of their procedures. These reports are included in the section on "Commercially Available Software" and include the following products:

* AutoBox (Automatic Forecasting Systems)
* Forecast Pro (Business Forecast Systems)
* ForecastX (John Galt)
* PP Autocast (Delphus)
* SmartForecasts (Smart Software)

## An evaluation

As is evident from our introduction, we have attempted to provide full information about the M3-Competition and its results, with a minimum of editorial assessment. The second part of the Special Issue, which will appear in the _International Journal of Forecasting_ in 2001, will provide detailed commentary by the study participants and other selected experts in the forecasting area. We do not expect even that commentary to be the final word on the subject and we encourage others to send in their comments. These communications may be either in the form of short papers to the _Journal_, where they will be reviewed in the usual way or, to maintain a quick turnaround and exchange of ideas, to the Institute's newsletter _Oracle_. We look forward to hearing from you.

## References

* Collopy & Armstrong (1992) Collopy, F., & Armstrong, J. S. (1992). Rule-based forecasting: Development and validation of an expert systems approach to combining time series extrapolations. _Management Science__38_, 1394-1414.
* Fildes et al. (1998) Fildes, R., Hibon, M., Makridakis, S., & Meade, N. (1998). Generalising about univariate forecasting methods: further empirical evidence with discussion. _International Journal of Forecasting__14_, 339-358.
* Fildes & Makridakis (1995) Fildes, R., & Makridakis, S. (1995). The impact of empirical accuracy studies on time series analysis and forecasting. _International Statistical Review__63_, 289-308.
* Fildes & Ord (2000) Fildes, R. and Ord, J.K. (2000). Forecasting competitions-their role in improving forecasting practice and research. In Hendry, D.F. and Clements, M.P. (eds) _A Companion to Economic Forecasting_. Blackwell, Oxford (to appear).
* Makridakis et al. (1982) Makridakis, S., Andersen, A., Carbone, R., Fildes, R., Hibon, M., Lewandowski, R., Newton, J., Parzen, E., & Winkler, R. (1982). The accuracy of extrapolation (time series) methods; Results of a forecasting competition. _Journal of Forecasting__1_, 111-153.
* Makridakis et al. (1993) Makridakis, S., Chatfield, C., Hibon, M., Lawrence, M., Mills, T., Ord, J. K., & Simmons, L. (1993). The M-2 Competition: A real-life judgmentally based forecasting study with discussion. _International Journal of Forecasting__9_, 5-29.
* Makridakis & Hibon (1979) Makridakis, S., & Hibon, M. (1979). Accuracy of forecasting: an empirical investigation (with discussion). _Journal of the Royal Statistical Society (A)__142_, 97-145.
* Meese & Geweke (1984) Meese, R., & Geweke, J. (1984). A comparison of autoregressive univariate forecasting procedures for macroeconomic time series. _Journal of Business and Economic Statistics__2_, 191-200.

Newbold, P., & Granger, C. W. J. (1974). Experience with forecasting univariate time-series and the combination of forecasts with discussion. _Journal of the Royal Statistical Society (A) 137_, 131-165.
* Parzen (1982) Parzen, E. (1982). ARARMA models for time series analysis and forecasting. _Journal of Forecasting 2_, 67-82.
* Reid (1969) Reid, D.J. (1969). _A comparative study of time series prediction techniques on economic data_', PhD Thesis, University of Nottingham, Nottingham, UK.
* Reid (1972) Reid, D.J. (1972). A comparison of forecasting techniques on economic time series. In Bramson, M.J., Helps, I.G., and Watson-Gandy, J.A.C.C. (eds) _Forecasting in Action_. Operational Research Society, Birmingham, UK.